variable "NAME" {}
variable "CIDR" {}
variable "AZ" {}
variable "SUBNET" {}
variable "PVT-SUBNET" {}
variable "wave-key" {
  type        = string
  default     = "inst-key"
  description = "Key-pair generated by Terraform"
}